info:
  name: Get DNS Configuration
  type: http
  seq: 5

http:
  method: GET
  url: "{{base_url}}/tailnet/{{tailnet}}/dns/configuration"
  auth:
    type: bearer
    token: "{{access_token}}"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
