info:
  name: Get Log Streaming Configuration
  type: http
  seq: 4

http:
  method: GET
  url: "{{base_url}}/tailnet/{{tailnet}}/logging/{{log_type}}/stream"
  auth:
    type: bearer
    token: "{{access_token}}"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
