info:
  name: Get Device Routes
  type: http
  seq: 3

http:
  method: GET
  url: "{{base_url}}/device/{{device_id}}/routes"
  auth:
    type: bearer
    token: "{{access_token}}"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
